### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by davesag** [gargol/swagger-express-validator#16]
Maybe I am holding it wrong, but I've installed the validator, deliberately broke some routes just to see what happened, and nothing happened.

Turned on the debugger.  Nothing there either.

My `appMaker`

```
const express = require('express')
const cors = require('cors')
const bodyParser = require('body-parser')
const YAML = require('yamljs')
const swaggerUi = require('swagger-ui-express')

const apiValidator = require('src/utils/apiValidator')
const rest = require('src/utils/rest')
const genericErrors = require('src/utils/genericErrors')
const docs = YAML.load('api.yml')

const makeApp = async () => {
  const app = express()
  app.use(cors())
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(docs))
  app.use(bodyParser.json())

  app.set('trust proxy', true) // needed to get the requesting ip
  // add any other middlewares here
  await rest(app) // apply the routes

  app.use(apiValidator(docs))
  app.use(genericErrors) // must be last
  return app
}
```

and `apivalidator`

```
const util = require('util')
const validator = require('swagger-express-validator')
const logger = require('src/utils/logger')

const common = (req, errors) =>
  `${req.method} ${req.originalUrl}\n ${util.inspect(errors)}`

const requestValidationFn = (req, data, errors) => {
  logger.error(`Request Invalid: ${common(req, errors)}`)
}

const responseValidationFn = (req, data, errors) => {
  logger.error(`Response Invalid: ${common(req, errors)}`)
}

const apiValidator = schema => {
  console.log('schema', schema)
  const config = {
    schema,
    validateRequest: true,
    validateResponse: true,
    requestValidationFn,
    responseValidationFn,
  }
  return validator(config)
}

module.exports = apiValidator
```

it's definitely getting the schema.  Any thoughts?

**Comment by davesag** [comment]
Further investigation.  Here's the extract from my `api.yml`

```
  /ping:
    get:
      tags:
        - "root"
      summary: "Get Server Information"
      description: "Returns information about the server"
      operationId: "ping"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ServerInfo"
```

`ServerInfo` is defined as

```
  ServerInfo:
    type: "object"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      version:
        type: "string"
      uptime:
        type: "number"
```

and I am deliberately sending back an extra value in my response, just to see the validator work

```
{
  "name": "my-project",
  "description": "Just a test project",
  "version": "1.0.0",
  "uptime": 6.431,
  "should": "not be here"
}
```

I get the following in the debug log
```
swagger-validator Processing: GET /ping +6s
  swagger-validator Request validation skipped: no matching request schema +3ms
  swagger-validator {"name":"my-project","description":"Just a test project","version":"1.0.0","uptime":6.431,"should":"not be here"} +3ms
  swagger-validator Response validation success +15ms
```

**Comment by davesag** [comment]
aha I have worked it out.  I just needed to define my `ServerInfo` object better

```
  ServerInfo:
    type: "object"
    required:
      - name
      - description
      - version
      - uptime
    additionalProperties: false
    properties:
      name:
        type: "string"
      description:
        type: "string"
      version:
        type: "string"
      uptime:
        type: "number"
```

so yes I was holding it wrong.
