### ISSUE TITLE
Excessive Travis dependencies

### ISSUE THREAD

**Issue by kibertoad** [gargol/swagger-express-validator#27]
```
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8 # C++11-compatible compiler for node > v4.0.0
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
- "export CXX=g++-4.8"
```

Are all those things needed for testing `swagger-express-validator`? I don't think it uses MySQL for anything.
